spring:
  docker:
    compose:
      enabled: true
      file: spring-boot-batch-cloud-task/compose.yml
  data:
    mongodb:
      uri: mongodb://localhost:27017

logging:
  logback:
    rollingpolicy:
      clean-history-on-start: true
  file:
    path: logs
    name: ${logging.file.path}/application.log
  level:
    ROOT: info
    #    '[org.springframework.data.mongodb.core.MongoTemplate]': debug
#    '[org.springframework.batch]': debug
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

application:
  batch:
    chunk-size: 100
    skip-limit: 10
    max-retries: 3
    backoff-initial-delay: PT3S
    backoff-multiplier: 2
    item-reader-page-size: 300
    partition-size: 16
    trigger.partitioning.threshold: 100